version: '3'

services:
  db:
    image: postgres
#  environment:
#    - POSTGRES_DB=shpacoo
#    - POSTGRES_USER=razhel
#    - POSTGRES_PASSWORD=!Poland123
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db1
