# Generated by Django 2.2.1 on 2019-05-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0002_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
