# Generated by Django 2.2.1 on 2019-08-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0003_auto_20190505_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrappedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
