# Generated by Django 2.2.1 on 2019-08-11 11:56

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0003_auto_20190505_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a task to record', max_length=100, verbose_name='Task name')),
                ('history', jsonfield.fields.JSONField(default={}, help_text='JSON containing the tasks history', verbose_name='History')),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Task Histories',
            },
        ),
    ]
