# Generated by Django 2.2.1 on 2019-08-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0004_scrappeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shpacoo_portal.Artist'),
        ),
    ]
