# Generated by Django 2.2.1 on 2019-08-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0005_auto_20190831_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shpacoo_portal.Artist'),
        ),
    ]
