# Generated by Django 2.2.1 on 2019-08-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shpacoo_portal', '0006_auto_20190831_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shpacoo_portal.Artist'),
        ),
    ]
